version: '3.8'

services:

  mysql-ponto:
    image: mysql
    container_name: "mysql-ponto"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "sistema_pontos"
    ports:
      - "3306:3306"
    volumes:
      - ./data/sistem-ponto/mysql-sistema-pontos:/var/lib/mysql


  ui-ponto:
    image: front-ponto:1.0
    container_name: "ui-ponto"
    depends_on:
      - sistema-ponto
    ports:
      - "8081:80"
    volumes:
      - ./data/sistem-ponto/front:/var/www/system-ponto
 
  sistema-ponto:
    depends_on:
      - mysql-ponto
    image: "sistema-ponto"
    container_name: "sistema-ponto"
    ports:
      - "8080:8080"
      - "8005:8005"
    environment:
      # Buildpacks environment variable to configure the number of threads in memory calculation
      - BPL_JVM_THREAD_COUNT=50
      # Buildpacks environment variable to enable debug through a socket on port 8001
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8005
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-ponto:3306/sistema_pontos
  

